name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [labeled]
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dump context
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log(context);
            console.log("==========================================================================================")
            console.log(context.payload);
            console.log("==========================================================================================")

      - name: Fake Tests
        run: |
          echo Hello there - I'm pretending I've run some tests!
          echo "Dubious manipulation to get a secret.... ${SOMETHING_SECRET:0:1} ${SOMETHING_SECRET:1:100}"
        env:
          SOMETHING_SECRET: ${{ secrets.SOMETHING_SECRET }}
