name: fake-extended-3

on:
  workflow_call:
    inputs:
      # prRepo:
      #   description: Name of the repo GitHub repo containing the ref (as org/repo )
      #   type: string
      prRef:
        description: The git ref to checkout
        type: string
      test1:
        description: testing params and conditions
        type: string
        required: false
      test2:
        description: testing params and conditions
        type: string
        required: false
    secrets:
      SOMETHING_SECRET:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # repository: ${{ inputs.prRepo }}
          ref: ${{ inputs.prRef }}

      - name: More output
        run: |
          echo
          echo "git SHA:    $(git rev-parse --abbrev-ref HEAD)"
          echo "git ref:    $(git rev-parse HEAD)"
          echo "github ref: ${GITHUB_REF}"

      - name: Test1
        if: ${{ inputs.test1 != '' }}
        run: |
          echo "Test1!"
      - name: Test2
        if: ${{ inputs.test2 == '' }}
        run: |
          echo "Not Test2!"

      - name: Fake extended tasks
        run: |
          set -e

          echo "Dubious manipulation to get a secret.... <start>${SOMETHING_SECRET:0:1} ${SOMETHING_SECRET:1:100}<end>"
          echo

          echo
          echo "Pretend that we're doing something more here - show output.txt for PR context :-)"
          cat "output.txt"

          echo "Sleeping to simulate work..."
          sleep 60s
        env:
          SOMETHING_SECRET: ${{ secrets.SOMETHING_SECRET }}
          # PR_REPO: ${{ inputs.prRepo }}
          PR_REF: ${{ inputs.prRef }}
