name: fake-extended

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fake extended tasks
        run: 
          echo "Pretend that we're doing something more here :-)"
          cat "output.txt"