name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dump context
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log(context);
            console.log("==========================================================================================")
            console.log(context.payload);
            console.log("==========================================================================================")

      - name: More output
        run: |
          echo Hello there!
          echo "Dubious manipulation to get a secret.... ${SOMETHING_SECRET:0:1} ${SOMETHING_SECRET:1:100}"

          echo
          echo "git SHA:    $(git rev-parse --abbrev-ref HEAD)"
          echo "git ref:    $(git rev-parse HEAD)"
          echo "github ref: ${GITHUB_REF}"
        env:
          SOMETHING_SECRET: ${{ secrets.SOMETHING_SECRET }}


  test:
    name: Fake tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fake building...
        run: |
          echo Hello there!
          echo "SOMETHING_SECRET: $SOMETHING_SECRET"
          echo "Dubious manipulation to get a secret.... ${SOMETHING_SECRET:0:1} ${SOMETHING_SECRET:1:100}"
          echo "ANOTHER_SECRET: $ANOTHER_SECRET"
          echo "Dubious manipulation to get another secret.... ${ANOTHER_SECRET:0:1} ${ANOTHER_SECRET:1:100}"
        env:
          SOMETHING_SECRET: ${{ secrets.SOMETHING_SECRET }}
          ANOTHER_SECRET: ${{ secrets.ANOTHER_SECRET }}


  run_test:
    name: Run deploy via workflow_call
    uses: ./.github/workflows/fake-extended-3.yml
    with:
      prRef: "refs/pull/${{ github.event.issue.number }}/merge"
      test1: ${{ secrets.ANOTHER_SECRET }}
      # prRef: ${{ needs.pr_commented.outputs.potentialMergeCommit }}
      # # prRef: ${{ needs.pr_commented.outputs.prRef }}
      # # prRepo: ${{ needs.pr_commented.outputs.prRepo }}
    secrets:
      SOMETHING_SECRET: ${{ secrets.SOMETHING_SECRET }}
