name: pr_comment_bot

on:
  issue_comment:
    types: [created]

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
# https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment


# https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs

jobs:

  pr_commented:
    name: PR comment
    # https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
    # (and https://docs.github.com/en/rest/reference/issues#comments)
    if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR') }}
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.check_command.outputs.result }}
      prRepo: ${{ steps.get_pr_details.outputs.prRepo }}
      prRef: ${{ steps.get_pr_details.outputs.prRef }}
      potentialMergeCommit: ${{ steps.get_pr_details.outputs.potentialMergeCommit }}
      not-md: ${{ steps.filter.outputs.not-md }}
    steps:
      - id: check_command
        name: Check for a command using GitHub script
        uses: actions/github-script@v6
        env:
          TEST: ${{ format('fmt-{0}-string', 
                      'value-here') }}
          SOMETHING_SECRET: ${{ secrets.SOMETHING_SECRET }}
        with:
          result-encoding: string
          script: |
            console.log(context);
            console.log("==========================================================================================")
            console.log(context.payload);
            console.log("==========================================================================================")

            //// https://docs.github.com/en/rest/reference/collaborators#check-if-a-user-is-a-repository-collaborator
            //const commentUsername = context.payload.comment.user.login;
            //const repoFullName = context.payload.repository.full_name;
            //const repoParts = repoFullName.split("/");
            //const repoOwner = repoParts[0];
            //const repoName = repoParts[1];
            //
            //let userHasWriteAccess = false;
            //try {
            //  console.log(`Checking if user "${commentUsername}" has write access to ${repoOwner}/${repoName} ...`)
            //  const result = await github.request('GET /repos/{owner}/{repo}/collaborators/{username}', {
            //    owner: repoOwner,
            //    repo: repoName,
            //    username: commentUsername
            //  });
            //  const userHasWriteAccess = result.status == 204;
            //  console.log(result);
            //} catch (err) {
            //  if (err.status !== 404){
            //    console.log(`Error checking if user has write access: ${err.status} (${err.response.data.message}) `)
            //  }
            //}
            //console.log("User has write access: " + userHasWriteAccess);
            //
            //if (!userHasWriteAccess){
            //  // only allow users with write access to run commands
            //  return "none";
            //}

            const commentBody = context.payload.comment.body;
            const commentFirstLine = commentBody.split("\n")[0];

            console.log("::set-output name=runSomething::true");
            switch (commentFirstLine.trim()){
              case "/test":
                console.log("Result: run-tests");
                return "run-tests";
              case "/help":
                console.log("Result: show-help");
                return "show-help";
              default:
                console.log("in default")
                return "none";
            }

      - name: Show result
        env:
          RUN_SOMETHING: ${{ steps.check_command.outputs.runSomething }}
        run: |
          echo "hi"
          echo "env var: ${RUN_SOMETHING}"
          echo "output: ${{ steps.check_command.outputs.runSomething }}"

      - name: Calcs
        id: calcs
        run: |
          echo "hi"
          echo "::set-output name=runSomething::true"

      - name: Show result2
        env:
          RUN_SOMETHING: ${{ steps.calcs.outputs.runSomething }}
        run: |
          echo "hi"
          echo "env var: ${RUN_SOMETHING}"
          echo "output: ${{ steps.calcs.outputs.runSomething }}"


      - name: Show Help
        if: ${{ steps.check_command.outputs.result == 'show-help' }}
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.event.repository.full_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Showing help on PR ${PR_NUMBER}"
          gh pr comment ${PR_NUMBER} --repo $REPO --body "Hello<br/><br/>You can use the following commands:<br/>    /test - run tests on a PR<br/>    /help - show this help"

      - id: get_pr_details
        name: Get PR details
        if: ${{ steps.check_command.outputs.result == 'run-tests' }}
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.event.repository.full_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Could look at moving this to GitHub Script action as well

          echo "Getting PR repo..."
          pr_owner=$(gh pr view $PR_NUMBER --repo $REPO --json headRepositoryOwner | jq -r .headRepositoryOwner.login)
          pr_repo=$(gh pr view $PR_NUMBER --repo $REPO --json headRepository | jq -r .headRepository.name)
          echo -e "\tPR from $pr_owner/$pr_repo"

          echo "Getting PR ref..."
          ref=$(gh pr view $PR_NUMBER --repo $REPO --json commits | jq -r ".[] | last | .oid")
          echo -e "\tLatest commit ref: $ref"
          echo

          potentialMergeCommit=$(gh pr view $PR_NUMBER --repo $REPO --json potentialMergeCommit | jq -r .potentialMergeCommit.oid)
          echo -e "\tpotentialMergeCommit: $potentialMergeCommit"
          echo


          echo "Setting outputs"
          echo "::set-output name=prRef::${ref}"
          echo "::set-output name=prRepo::${pr_owner}/${pr_repo}"
          echo "::set-output name=potentialMergeCommit::${potentialMergeCommit}"
          echo "Done"

          echo ${GITHUB_REF}



      - name: Checkout
        if: |
          ${{ steps.check_command.outputs.result == 'run-tests'
              || steps.check_command.outputs.result == 'force-approve' }}
        uses: actions/checkout@v2
        with:
          # repository: ${{ steps.get_pr_details.outputs.prRepo }}
          # ref: ${{ steps.get_pr_details.outputs.prRef }}
          ref: ${{ steps.get_pr_details.outputs.potentialMergeCommit }}
          persist-credentials: false

      # - name: Checkout (CLI)
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PR_REPO: ${{ steps.get_pr_details.outputs.prRepo }}
      #     PR_REF: ${{ steps.get_pr_details.outputs.potentialMergeCommit }}
      #     # PR_REF: ${{ steps.get_pr_details.outputs.prRef }}
      #   run: |
      #     #
      #     # NOTE: Here we are using the latest PR commit, i.e. we're not merging with main
      #     #       We could merge main (and even test if the PR is mergable before kicking off the run)
      #     #
      #     git status
      #     echo "-------------------------------------"
      #     git rev-parse HEAD
      #     git rev-parse --abbrev-ref HEAD
      #     echo "-------------------------------------"

      #     echo "Load PR code..."
      #     git config advice.detachedHead false
      #     git remote add fork https://github.com/${PR_REPO}
      #     git remote update
      #     git checkout ${PR_REF}


      #     echo "-------------------------------------"
      #     git status
      #     echo "-------------------------------------"
      #     git rev-parse HEAD
      #     git rev-parse --abbrev-ref HEAD

      - name: Test script
        run: |
          echo "running script..."
          scripts/test.sh
          echo "done"


      - name: Info
        run: |
          git status
          echo "-------------------------------------"
          git rev-parse --abbrev-ref HEAD
      - uses: dorny/paths-filter@v2
        id: filter
        if: |
          ${{ steps.check_command.outputs.result == 'run-tests' 
          || steps.check_command.outputs.result == 'force-approve' }}
        with:
          base: main
          ref: ${{ steps.get_pr_details.outputs.prRef }}
          filters: |
            not-md:
              # we need to check for changes in files other than *.md
              - '**/!(*.md)'

      - name: Comment with link to run
        if: ${{ steps.check_command.outputs.result == 'run-tests' }}
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.event.repository.full_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
        run: |
          echo "Showing help on PR ${PR_NUMBER}"
          gh pr comment ${PR_NUMBER} --repo $REPO --body "Running tests: https://github.com/${REPO}/actions/runs/${RUN_ID}"

  debug:
    needs: [pr_commented]
    name: debug
    runs-on: ubuntu-latest
    steps:
      - name: Show result
        run: |
          echo "hi"
          echo "command: ${{ needs.pr_commented.outputs.command }}"
          echo "not-md: ${{ needs.pr_commented.outputs.not-md }}"

  run_test:
    needs: [pr_commented]
    if: ${{ needs.pr_commented.outputs.command == 'run-tests' && needs.pr_commented.outputs.not-md == 'true'}}
    name: Run deploy
    uses: ./.github/workflows/fake-extended-3.yml
    with:
      prRef: "refs/pull/${{ github.event.issue.number }}/merge"
      test1: something
      # prRef: ${{ needs.pr_commented.outputs.potentialMergeCommit }}
      # # prRef: ${{ needs.pr_commented.outputs.prRef }}
      # # prRepo: ${{ needs.pr_commented.outputs.prRepo }}
    secrets:
      SOMETHING_SECRET: ${{ secrets.SOMETHING_SECRET }}
