on: issue_comment

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
# https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment


jobs:
  pr_commented:
    name: PR comment
    # https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
    # (and https://docs.github.com/en/rest/reference/issues#comments)
    if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR') }}
    runs-on: ubuntu-latest
    steps:
      # TODO https://docs.github.com/en/actions/advanced-guides/using-github-cli-in-workflows
      - name: check_command
        run: |
          set -e
          echo "A comment on PR $NUMBER for $REPO"
          echo "Comment:"
          echo "$COMMENT_BODY"
          echo 

          got_command=$(echo "$COMMENT_BODY" | grep -q /test; echo $?)
          if [[ "$got_command" != "0" ]]; then
            echo "command not found - ignoring"
            exit 0
          fi

          echo "gh version"
          gh --version
          echo

          echo "get headRef"
          ref=$(gh pr view $NUMBER --repo $REPO --json headRefName | jq -r .headRefName)
          echo "Ref: $ref"
          echo

          echo "run workflow"
          echo "REPO: $REPO"
          # gh workflow run fake-extended --repo $REPO --ref $ref
          gh api -X POST repos/stuartleeks/actions-playground/actions/workflows/fake-extended.yml/dispatches -F ref=$ref
          echo

          echo "add comment"
          gh pr comment $NUMBER --repo $REPO --body "started extended workflow"
        env:
          NUMBER: ${{ github.event.issue.number }}
          ISSUE_URL: ${{ github.event.issue.url }}
          REPO: ${{ github.event.repository.full_name }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
